(package "flycheck-elsa" "1.0.0" "Flycheck for Elsa")

(website-url "https://github.com/emacs-elsa/flycheck-elsa")
(keywords "convenience")

(package-file "flycheck-elsa.el")

(files "flycheck-elsa-*.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source 'gnu)
(source 'melpa)

(depends-on "emacs" "25")
(depends-on "flycheck" "0.14")
(depends-on "seq" "2.0")

(development
 (depends-on "trinary" "0.0.1")
 (depends-on "elsa" "0.0.1"))
